### PR TITLE
Migrate imt rust implementation from zk-kit to zk-kit.rs repo

### LINKED ISSUE #3: Move IMT crate from zk-kit to zk-kit.rust
**Describe the package you'd like**

An IMT implementation in Rust has already been added to the [zk-kit repository](https://github.com/privacy-scaling-explorations/zk-kit/pull/134). However, since the Rust crates should stay in this repository now, the code should be moved here.

### PR DESCRIPTION
**Pull request by Arch0125**
## Description

This PR adds Rust implmentation of IMT with the following methods included insert/update/delete/create-proof/verify-proof

## Related Issue

Closes #3  

## Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

### Test coverage
- [x] **Test New IMT Instance**
  - Description: Ensure that a new `IMT` instance is created successfully.

- [x] **Test Leaf Insertion**
  - Description: Check if new leaves can be inserted into the tree.

- [x] **Test Leaf Deletion**
  - Description: Test the deletion functionality of a leaf in the tree.

- [x] **Test Leaf Update**
  - Description: Ensure that a leaf in the tree can be updated correctly.

- [x] **Test Create and Verify Proof**
  - Description: Create a Merkle proof for a leaf and verify its correctness.

- [x] **Should Not Initialize with Too Many Leaves**
  - Description: The tree should not initialize if the number of leaves exceeds `arity ^ depth`.

- [x] **Should Not Insert in Full Tree**
  - Description: Test that leaves cannot be inserted into a full tree.

- [x] **Should Not Delete Nonexistent Leaf**
  - Description: Ensure that attempting to delete a nonexistent leaf results in an error.

### CODE REVIEW

**Comment by Arch0125** [comment]
@cedoor lmk if this looks good

**Review by sripwoud — APPROVED** [review]
utACK

Thanks for migrating that crate to this repo

**Comment by cedoor** [comment]
Thanks both @Arch0125 for working on it and @sripwoud for reviewing it 🙏🏽

**Comment by Arch0125** [comment]
@cedoor @sripwoud let me know what all implementations needed to be added in the repo, would love to work it

**Comment by cedoor** [comment]
@Arch0125 Created a new issue rn: https://github.com/privacy-scaling-explorations/zk-kit.rust/issues/8. More will follow

**Pull request merged**
