### PR TITLE
move pmtree into zk-kit

### LINKED ISSUE #4: Move pmtree implementation from RLN to zk-kit.rust
**Describe the package you'd like**

[`pmtree`](https://github.com/Rate-Limiting-Nullifier/pmtree) (Persistent Merkle Tree) is an optimized, sparse, fixed-size Merkle tree implementation in Rust. The code is currently in the RLN repository. It will, however, be moved to ZK-Kit as part of a general effort by PSE to move reusable libraries and implementation to one place.

### PR DESCRIPTION
**Pull request by wiasliaw**
## Description

Closes #4.

## Other information

This PR moved [pmtree](https://github.com/Rate-Limiting-Nullifier/pmtree) into zk-kit. Some of the information should be check:

- [ ] License: There are two different LICENSE in pmtree and need to confirm whether to use the MIT license or follow pmtree's license.
- [ ] README: Since zk-kit-pmt has not been released, badges may be unavailable.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have run `make lint` and `cargo build --release` without getting any errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by curryrasul — CHANGES_REQUESTED** [review]
As far as I can see, there're no changes in the code, so everything's okay.
The only thing I have in mind - is that something should be done w namings. 
Because the name of the crate is `pmt` , then in README it's said `Sparse Merkle Tree` - while at the same time there's also crate `smt` where it is said `Sparse Merkle Tree`. Looks like a duplicate for users imo.

Thanks for integration work btw ;)

**Comment by curryrasul** [comment]
@wiasliaw 
> License: There are two different LICENSE in pmtree and need to confirm whether to use the MIT license or follow pmtree's license.

For this - It's common practice to include both Apache2.0 and MIT Licenses , that's why we made it. It's more flexible for users

**Comment by wiasliaw** [comment]
Hi, @curryrasul 

> For this - It's common practice to include both Apache2.0 and MIT Licenses , that's why we made it. It's more flexible for users.

My question is that pmtree includes both Apache2.0 and MIT Licenses and zk-kit-rust only include MIT License. It is confusing which one to follow.

**Comment by cedoor** [comment]
> My question is that pmtree includes both Apache2.0 and MIT Licenses and zk-kit-rust only includes MIT License. It is confusing which one to follow.

The license in the root folder is just about the monorepo. All packages should still have their own specific license as they're published as crates tho.

If that's confusing we could add some documentation in the main README file I think.

**Comment by wiasliaw** [comment]
I had added both mit and apahce licenses and fixed the readme.

---

> If that's confusing we could add some documentation in the main README file I think.

It might confuse ppl that there's a license in the root but monorepos have their own license.

**Comment by cedoor** [comment]
@wiasliaw could you check if the code is well formatted? 1 workflow is not passing.

@sripwoud the error in the CI workflow is about code format right?

**Comment by wiasliaw** [comment]
@cedoor It looks like packages listed in Cargo.toml should be sorted.

**Comment by cedoor** [comment]
> @cedoor It looks like packages listed in Cargo.toml should be sorted.

Oh yea! It should be ok now right? Ready to be merged?

**Comment by wiasliaw** [comment]
Yes.

**Review by cedoor — APPROVED** [review]

**Comment by cedoor** [comment]
Hey@curryrasul, could you take a look again and approve it?

**Review by curryrasul — APPROVED** [review]
LGTM!

**Pull request merged**
